FROM eyedeekay/acng-i2p
RUN echo "https://deb.torproject.org/torproject.org" | tee /etc/apt-cacher-ng/backends_tor
RUN gpg --keyserver hkp://pool.sks-keyservers.net:80 --recv-keys EE8CBC9E886DDD89; \
	gpg -a --export EE8CBC9E886DDD89 | apt-key add -
RUN echo "Remap-tor: http://tor.repo ; file:backends_tor" | tee -a /etc/apt-cacher-ng/acng.conf
RUN echo "PrecacheFor: tor/*/*/*/*/Packages*" | tee -a /etc/apt-cacher-ng/acng.conf
