FROM hoarder-apt-cache
WORKDIR /home/packagecacher/sources
#RUN apt-cacher-ng -c /etc/apt-cacher-ng/ & sleep 3 && \
#        apt-get update && \
#        for p in $(cat /home/packagecacher/packages.list | tr "\n" " "); do \
#                su packagecacher -c "apt-get source -yq $p"; \
#                done
